"""create crop guides table

Revision ID: 22fa613404b9
Revises: caef80084e68
Create Date: 2026-07-30 11:06:25.914974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fa613404b9'
down_revision: Union[str, Sequence[str], None] = 'caef80084e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_guides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crop_name', sa.String(length=255), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('suitable_season', sa.String(length=255), nullable=True),
    sa.Column('soil_type', sa.String(length=255), nullable=True),
    sa.Column('climate', sa.String(length=255), nullable=True),
    sa.Column('seed_selection', sa.Text(), nullable=True),
    sa.Column('irrigation', sa.Text(), nullable=True),
    sa.Column('fertilizer_guide', sa.Text(), nullable=True),
    sa.Column('common_diseases', sa.Text(), nullable=True),
    sa.Column('pest_control', sa.Text(), nullable=True),
    sa.Column('harvesting', sa.Text(), nullable=True),
    sa.Column('storage', sa.Text(), nullable=True),
    sa.Column('market_information', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_crop_guides_crop_name'), 'crop_guides', ['crop_name'], unique=True)
    op.create_unique_constraint(None, 'fertilizer_history', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fertilizer_history', type_='unique')
    op.drop_index(op.f('ix_crop_guides_crop_name'), table_name='crop_guides')
    op.drop_table('crop_guides')
    # ### end Alembic commands ###
