"""create disease history table

Revision ID: 3e789481e350
Revises: fe6e9521c546
Create Date: 2026-07-30 11:01:25.462128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e789481e350'
down_revision: Union[str, Sequence[str], None] = 'fe6e9521c546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=False),
    sa.Column('crop_name', sa.String(length=255), nullable=True),
    sa.Column('predicted_disease', sa.String(length=255), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=True),
    sa.Column('prevention', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_disease_history_user_id'), 'disease_history', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'chat_conversations', ['id'])
    op.create_unique_constraint(None, 'chat_messages', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='unique')
    op.drop_constraint(None, 'chat_conversations', type_='unique')
    op.drop_index(op.f('ix_disease_history_user_id'), table_name='disease_history')
    op.drop_table('disease_history')
    # ### end Alembic commands ###
