"""create weather history table

Revision ID: 472615f1ceea
Revises: 3e789481e350
Create Date: 2026-07-30 11:03:04.499822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '472615f1ceea'
down_revision: Union[str, Sequence[str], None] = '3e789481e350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('weather_condition', sa.String(length=255), nullable=False),
    sa.Column('agriculture_advice', sa.String(length=1024), nullable=True),
    sa.Column('searched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_weather_history_user_id'), 'weather_history', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'disease_history', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disease_history', type_='unique')
    op.drop_index(op.f('ix_weather_history_user_id'), table_name='weather_history')
    op.drop_table('weather_history')
    # ### end Alembic commands ###
