"""create fertilizer history table

Revision ID: caef80084e68
Revises: 472615f1ceea
Create Date: 2026-07-30 11:04:36.864111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caef80084e68'
down_revision: Union[str, Sequence[str], None] = '472615f1ceea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fertilizer_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('crop_name', sa.String(length=255), nullable=False),
    sa.Column('soil_type', sa.String(length=255), nullable=False),
    sa.Column('nitrogen', sa.Float(), nullable=False),
    sa.Column('phosphorus', sa.Float(), nullable=False),
    sa.Column('potassium', sa.Float(), nullable=False),
    sa.Column('ph_value', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('rainfall', sa.Float(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('recommended_fertilizer', sa.String(length=255), nullable=False),
    sa.Column('recommended_quantity', sa.String(length=255), nullable=True),
    sa.Column('application_time', sa.String(length=255), nullable=True),
    sa.Column('safety_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_fertilizer_history_user_id'), 'fertilizer_history', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'weather_history', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'weather_history', type_='unique')
    op.drop_index(op.f('ix_fertilizer_history_user_id'), table_name='fertilizer_history')
    op.drop_table('fertilizer_history')
    # ### end Alembic commands ###
